global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Xml.Serialization;
global using Emyfreya.Steam.Web.Abstractions;
global using Emyfreya.Steam.Web.Api.Models;
global using Emyfreya.Steam.Web.Store.Models;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Refit;
