global using System.Runtime.InteropServices;
global using System.Text;
global using Emyfreya.Steam.Abstractions;
global using Emyfreya.Steam.Desktop;
global using Emyfreya.Steam.Desktop.Models.Errors;
global using Emyfreya.Steam.Models;
global using Emyfreya.Steam.Models.Errors;
global using FluentResults;
global using Microsoft.Win32;
